reexport const products = [
  {
    id: 1,
    name: "Spinash",
    description: "good spanish",
    price: 49.99,
    src: "https://imgur.com/aEsf5Gj.jpg",
    type: "product",
  },
  {
    id: 2,
    name: "Squash",
    description: "good spanish",
    price: 199,
    src: "https://imgur.com/tH30Ekv.jpg",
    type: "demand",
  },
  {
    id: 3,
    description: "good spanish",
    name: "Tomato",
    price: 300,
    src: "https://imgur.com/LDl9Aki.jpg",
    type: "product",
  },
  {
    id: 4,
    name: "Cabbage",
    price: 300,
    src: "https://imgur.com/aEsf5Gj.jpg",
    type: "product",
  },
  // {
  //   id: 5,
  //   name: "Spinash",
  //   price: 49.99,
  //   src: "https://imgur.com/aEsf5Gj.jpg",
  //   type: "product",
  // },
  {
    id: 6,
    name: "Squash",
    price: 199,
    src: "https://imgur.com/tH30Ekv.jpg",
    type: "demand",
  },
  {
    id: 7,
    name: "Tomato",
    price: 300,
    src: "https://imgur.com/LDl9Aki.jpg",
    type: "product",
  },
  {
    id: 4,
    name: "Cabbage",
    price: 300,
    src: "https://imgur.com/aEsf5Gj.jpg",
    type: "demand",
  },
];
